services:
  prometheus:
    extends:
      file: ./prometheus.yml
      service: prometheus
    profiles:
      - default
      - prometheus
      - grafana
  grafana:
    extends:
      file: ./grafana.yml
      service: grafana
    profiles:
      - default
      - grafana
  zipkin:
    extends:
      file: ./zipkin.yml
      service: zipkin
    profiles:
      - default
      - zipkin
  minio:
    extends:
      file: ./minio.yml
      service: minio
    profiles:
      - default
      - minio
