spring:
  docker:
    compose:
      enabled: true
      file: ./docker/docker-compose.yml
      profiles:
        active:
          - grafana
          - zipkin

  cloud:
    gateway:
      routes:
        - id: find-ongoing-campaign-rest
          uri: http://localhost:8082
          predicates:
            - Path=/v1/campaign/ongoing
        - id: find-campaign-rest
          uri: http://localhost:8082
          predicates:
            - Path=/v1/campaign/**
        - id: find-ongoing-campaign-grpc
          uri: https://localhost:6565
          predicates:
            - Path=/protobuf.CampaignService/findOngoingCampaign
          filters:
            - AddResponseHeader=X-Request-header, header-value
        - id: find-campaign-grpc
          uri: https://localhost:6565
          predicates:
            - Path=/protobuf.CampaignService/findCampaign
          filters:
            - AddResponseHeader=X-Request-header, header-value

server:
  port: 8080
  ssl:
    key-store-type: PKCS12
    key-store: classpath:client-cert.p12
    key-store-password: password
    key-password: password

logging:
  level:
    com:
      example: debug
