spring:
  application:
    name: application-spring-cloud-aws-client
  docker:
    compose:
      enabled: false
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-1
      kms:
        master-key: ${AWS_KMS_MASTER_KEY}
      s3:
        region: ap-northeast-1
        bucket: ${AWS_S3_BUCKET_NAME}
        encrypted-bucket: ${AWS_S3_ENCRYPTED_BUCKET_NAME}
