spring:
  application:
    name: grpc-application-server
  mvc:
    throw-exception-if-no-handler-found: true
    format:
      date: iso
  web:
    resources:
      add-mappings: false

server:
  port: 8081
  shutdown: graceful
  compression:
    enabled: true

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

grpc:
  security:
    auth:
      enabled: false
  shutdownGrace: 30
