spring:
  application:
    name: application-server
  mvc:
    throw-exception-if-no-handler-found: true
    format:
      date: iso
  web:
    resources:
      add-mappings: false

server:
  port: 8082
  shutdown: graceful
  compression:
    enabled: true

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
  packagesToScan: com.example.endpoint
  pathsToMatch: /v1/**
