spring:
  application:
    name: application-server
  threads:
    virtual:
      enabled: true
  mvc:
    problemdetails:
      enabled: true
  web:
    resources:
      add-mappings: false
  docker:
    compose:
      enabled: false

server:
  shutdown: graceful
  compression:
    enabled: true

management:
  endpoints:
    access:
      default: none
    web:
      exposure:
        include:
          - "health"
          - "metrics"
          - "prometheus"
  endpoint:
    health:
      access: read_only
      probes:
        enabled: true
    metrics:
      access: read_only
    prometheus:
      access: read_only
  metrics:
    tags:
      application: ${spring.application.name}
  observations:
    key-values:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
  packagesToScan: com.example.endpoint
  pathsToMatch: /v1/**
