spring:
  application:
    name: application-client
  main:
    web-application-type: none

management:
  endpoints:
    access:
      default: none
  tracing:
    sampling:
      probability: 1.0

grpc:
  enabled: false
  security:
    auth:
      enabled: false

external:
  gateway-server:
    schema: ${GATEWAY_SERVER_SCHEMA}
    domain: ${GATEWAY_SERVER_DOMAIN}
    port: ${GATEWAY_SERVER_PORT}
