spring:
  application:
    name: application-grpc-client
  main:
    web-application-type: none

management:
  endpoints:
    enabled-by-default: false
  tracing:
    sampling:
      probability: 1.0

grpc:
  enabled: false
  security:
    auth:
      enabled: false
